"""Check proof ownership and status in the thesis's mathematical environments."""

import re

KINDS = "theorem|proposition|lemma|corollary|claim|construction|conjecture"
EVENT = re.compile(r"\\(begin|end)\{(" + KINDS + r"|proof)\}|\\(?:sub)*section\*?\{")
TITLE = re.compile(r"\s*(\[(?:[^][]|\[[^]]*\])*\])?")
LABEL = re.compile(r"\s*\\label\{([^}]+)\}")


def strip_comments(source):
    # An even number of preceding backslashes leaves % as a comment marker.
    return re.sub(r"(?<!\\)((?:\\\\)*)%[^\n]*", r"\1", source)


def check_proof_status(sources, proof_source="chapters/app_proofs.tex"):
    statements, proofs, errors = {}, {}, []
    for filename, raw in sources.items():
        source = strip_comments(raw)
        stack, pending = [], None
        for event in EVENT.finditer(source):
            action, kind = event.groups()
            if action is None:  # A new section cannot inherit an inline proof owner.
                pending = None
                continue
            if action == "begin":
                header = TITLE.match(source, event.end())
                title = (header.group(1) or "")[1:-1]
                start = header.end()
                label_match = LABEL.match(source, start)
                label = label_match.group(1) if label_match else None
                owner = None
                if kind == "proof":
                    targets = re.findall(r"\\Cref\{([^}]+)\}", title)
                    # A named proof belongs exclusively to its explicit target.
                    owner = [x.strip() for t in targets for x in t.split(",")] if targets else ([pending] if pending else [])
                pending = None
                stack.append((kind, title, label, start, owner))
            elif not stack or stack[-1][0] != kind:
                errors.append(f"UNBALANCED PROOF ENVIRONMENT: {filename}: {kind}")
            else:
                _, title, label, start, owner = stack.pop()
                if kind == "proof":
                    if filename == proof_source and source[start:event.start()].strip():
                        for target in owner:
                            proofs.setdefault(target, []).append(title)
                    pending = None
                else:
                    if label:
                        statements[label] = (kind, title)
                    elif kind == "conjecture":
                        errors.append(f"UNLABELLED CONJECTURE: {filename}")
                    pending = label
        if stack:
            errors.append(f"UNCLOSED PROOF ENVIRONMENT: {filename}: {stack[-1][0]}")

    for label, (kind, title) in statements.items():
        if r"\aimedal" in title or r"\conditional" in title:
            if kind != "conjecture" or "with proof" not in title:
                errors.append(f"UNQUALIFIED PROOF STATUS: {label}")
        if kind != "conjecture":
            continue
        expected = "Conditional proof" if r"\conditional" in title else "Proposed proof"
        headings = proofs.get(label, [])
        if "with proof" in title and not headings:
            errors.append(f"CONJECTURE WITHOUT PROOF: {label}")
        for heading in headings:
            if not heading.startswith(expected):
                errors.append(f"PROOF STATUS DESYNC: {label}: {heading}")
    return errors


SECTION_OR_CONJECTURE = re.compile(
    r"\\(?:sub)*section\*?\{((?:[^{}]|\{[^{}]*\})*)\}|\\begin\{conjecture\}")


def conjecture_index(sources):
    """Return (label, claim, section) for every conjecture, in source order.

    The claim is the environment's own optional title with its status suffix
    removed, so the index cannot drift from the heading it indexes: renaming a
    conjecture renames its row. Comment stripping and the title and label
    patterns are shared with :func:`check_proof_status`, which separately
    guarantees that each of these carries a proposed proof and the badge.
    """
    rows = []
    for filename in sorted(sources):
        source = strip_comments(sources[filename])
        section = ""
        for event in SECTION_OR_CONJECTURE.finditer(source):
            if event.group(1) is not None:  # A sectioning command, not a statement.
                section = event.group(1).strip()
                continue
            header = TITLE.match(source, event.end())
            title = (header.group(1) or "")[1:-1]
            label_match = LABEL.match(source, header.end())
            if not label_match:
                continue  # check_proof_status reports the unlabelled case.
            claim = re.sub(r",\s*(with proof|conditional\b).*", "", title).strip()
            rows.append((label_match.group(1), claim, section))
    return rows


def conjecture_table(rows):
    """Render :func:`conjecture_index` rows as the body of a LaTeX table."""
    lines = [
        "% Generated by check_proof_status.py --table. Do not edit by hand.",
        r"\begin{tabularx}{\textwidth}{@{}lXX@{}}",
        r"\toprule",
        r"Statement & Claim & Section \\",
        r"\midrule",
    ]
    lines += [rf"\Cref{{{label}}} & {claim} & {section} \\" for label, claim, section in rows]
    lines += [r"\bottomrule", r"\end{tabularx}"]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    import glob
    import sys
    from pathlib import Path

    root = Path(__file__).resolve().parent
    rows = conjecture_index({
        name: (root / name).read_text(encoding="utf-8")
        for name in sorted(glob.glob("chapters/*.tex", root_dir=root))
    })
    if "--table" in sys.argv:
        out = root / "figures" / "conjecture_table.tex"
        out.write_text(conjecture_table(rows), encoding="utf-8")
        print(f"{out.relative_to(root)}: {len(rows)} conjectures")
    else:
        for label, claim, section in rows:
            print(f"{label}: {claim} [{section}]")
