#!/usr/bin/env python3
"""The four variant-bound grids, checked against the panel data and the table.

Backs the four sidewaysfigures of app_proofs.tex (sec:variant-grids):
fig:variant-bounds-m3-graphs, fig:variant-bounds-m3-hyper,
fig:variant-bounds-m6-graphs and fig:variant-bounds-m6-hyper.  Those are PNGs,
so a caption/label sweep says nothing about what is drawn inside them.  This
script asks three separate questions of each grid.

  (a) Do the eight panels agree with tab:variant-values, cell by cell?  The
      table is generated by variant_value_tables() and the figure by
      plot_variant_grid(), and both read gather_variant_grid(), but neither
      reads the other, so a disagreement is a real defect.  Every printed cell
      is matched to its panel: a bold vtExact cell to a completed enumeration
      at that n and the same value, a vtProved or vtConjectured cell to the
      drawn curve at that n, and a vtOpen cell to a witness that is at least
      as large as the printed lower bound.

  (b) Do the panels obey what the captions say they mean?  A panel whose
      status word is "conjectured" must carry a curve and a panel called
      "open" must not, no exact square, search circle or construction mark may
      sit above a curve the caption calls an upper bound, and no search circle
      may sit above a completed enumeration.

  (c) Is the committed PNG the one this data draws?  Each grid is redrawn into
      a temporary directory and compared by SHA-256 with the file in figures/.

The panels come from the frozen machine record, so nothing here starts a
search.  A missing key is an error rather than a recomputation, which is what
makes the comparison a check and not a rerun.

Run from program/:  ../.venv/bin/python3 scripts/verify_variant_grids.py
"""
import hashlib
import re
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import make_figures as mf                                    # noqa: E402
from make_figures import FIGURES                             # noqa: E402
from erdos915_unified import plot_variant_grid               # noqa: E402

TABLE = FIGURES / "variant_table_all.tex"
NS = list(range(2, 9))                                       # the table's columns
HALVES = ((0, 2, "graphs", "simple and multigraph models"),
          (2, 4, "hypergraphs", "hypergraph and multihypergraph models"))

CELL = re.compile(r"\\textcolor\{(vt\w+)\}\{(.*)\}\s*$")
STATUS = re.compile(r"\\textcolor\{vt\w+\}\{(proved|conjectured|open)\}")


def table_rows(m: int) -> list[str]:
    """The sixteen value rows printed under the m block of tab:variant-values."""
    block = TABLE.read_text().split(rf"\textbf{{$m={m}$}}")[1]
    nxt = re.search(r"\\textbf\{\$m=\d+\$\}", block)
    rows = [line for line in (block[:nxt.start()] if nxt else block).splitlines()
            if r"\textcolor{vt" in line]
    assert len(rows) == 16, f"m={m}: {len(rows)} value rows, expected 16"
    return rows


def parse_row(line: str):
    """(status word, one (colour, is bold, number) triple per column)."""
    parts = [p.strip().rstrip("\\").strip() for p in line.split("&")]
    cells = []
    for raw in parts[-len(NS):]:
        if raw == "":
            cells.append(None)                               # the n=2 hypergraph blank
            continue
        cell = CELL.match(raw)
        cells.append((cell.group(1), cell.group(2).startswith(r"\textbf{"),
                      int(re.search(r"(\d+)", cell.group(2)).group(1))))
    return STATUS.search(line).group(1), cells


def check_half(m: int, panels: list[dict], lo: int, hi: int, stem: str,
               subtitle: str, scratch: Path) -> int:
    rows = table_rows(m)[lo * 4:lo * 4 + 8]
    bad = 0
    for idx, (line, panel) in enumerate(zip(rows, panels[lo * 4:lo * 4 + 8])):
        where = f"m={m} {stem} row {idx}"
        status, cells = parse_row(line)
        exact = dict(zip(*panel["exact"])) if panel["exact"][0] else {}
        search = dict(zip(*panel["search"]))
        construction = dict(zip(*panel["construction"]))
        kind = "conj" if "conj" in panel else ("proved" if "proved" in panel else None)
        curve = dict(zip(*panel[kind])) if kind else {}

        if status != panel["status"]:
            print(f"{where}: table says {status!r}, panel says {panel['status']!r}")
            bad += 1
        if panel["status"] == "conjectured" and kind != "conj":
            print(f"{where}: conjectured, but no conjectural curve is drawn")
            bad += 1
        if panel["status"] == "open" and kind is not None:
            print(f"{where}: open, but a {kind} curve is drawn")
            bad += 1

        for n, cell in zip(NS, cells):
            if cell is None:
                if n in exact or n in search:
                    print(f"{where} n={n}: blank cell, but the panel has data")
                    bad += 1
                continue
            colour, bold, printed = cell
            if n in exact:
                if not bold or colour != "vtExact" or printed != exact[n]:
                    print(f"{where} n={n}: printed {cell}, enumerated {exact[n]}")
                    bad += 1
            elif bold:
                print(f"{where} n={n}: bold cell with no enumeration behind it")
                bad += 1
            elif curve:
                want = "vtProved" if kind == "proved" else "vtConjectured"
                if printed != curve[n]:
                    print(f"{where} n={n}: printed {printed}, curve {curve[n]}")
                    bad += 1
                if colour != want:
                    print(f"{where} n={n}: coloured {colour} under a {kind} curve")
                    bad += 1
            else:
                if colour != "vtOpen":
                    print(f"{where} n={n}: open row, cell coloured {colour}")
                    bad += 1
                if printed > max(search.get(n, 0), construction.get(n, 0)):
                    print(f"{where} n={n}: lower bound {printed} exceeds every witness")
                    bad += 1

        for name, points in (("exact", exact), ("search", search),
                             ("construction", construction)):
            for n, value in points.items():
                if n in curve and value > curve[n]:
                    print(f"{where} n={n}: {name} {value} above the curve {curve[n]}")
                    bad += 1
        for n, value in search.items():
            if n in exact and value > exact[n]:
                print(f"{where} n={n}: search {value} above enumeration {exact[n]}")
                bad += 1

    committed = FIGURES / f"variant_bounds_m{m}_{stem}.png"
    redrawn = scratch / committed.name
    plot_variant_grid(panels, path=redrawn, m=m, row_range=(lo, hi),
                      fontsize_scale=1.25, subtitle=subtitle)
    old = hashlib.sha256(committed.read_bytes()).hexdigest()
    new = hashlib.sha256(redrawn.read_bytes()).hexdigest()
    if old != new:
        print(f"{committed.name}: committed {old[:16]}, redrawn {new[:16]}")
        bad += 1
    print(f"{committed.name}: {'identical to the redraw' if old == new else 'DIFFERS'}")
    return bad


def main() -> int:
    # figures/ sits beside program/ in the repository and is not part of the
    # hand-in bundle, which carries main.pdf and program/ only.  Say so rather
    # than failing inside a read.
    if not TABLE.exists():
        print(f"{TABLE} is missing: run this from a checkout of the repository,"
              " not from the hand-in bundle.")
        return 1
    bad = 0
    with tempfile.TemporaryDirectory() as tmp:
        for m in (3, 6):
            panels = mf.gather_variant_grid(m=m)
            assert len(panels) == 16, len(panels)
            for lo, hi, stem, subtitle in HALVES:
                bad += check_half(m, panels, lo, hi, stem, subtitle, Path(tmp))
    print(f"{'no mismatches' if bad == 0 else str(bad) + ' mismatches'}"
          " across the four grids")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
